language: php
php:
    - 5.3
    - 5.4
env:
    - WP_VERSION=master WP_MULTISITE=0
    - WP_VERSION=3.4.2 WP_MULTISITE=0
    - WP_VERSION=master WP_MULTISITE=1
    - WP_VERSION=3.4.2 WP_MULTISITE=1
before_script:
    # Install CodeSniffer
    - pear install --alldeps PHP_CodeSniffer
    - phpenv rehash
    - git clone git://github.com/mrchrisadams/WordPress-Coding-Standards.git $(pear config-get php_dir)/PHP/CodeSniffer/Standards/WordPress
    - wget https://raw.github.com/tierra/wordpress-plugin-tests/setup/setup.sh
    - source setup.sh
script:
    - phpcs --standard=WordPress ./src
    - phpunit