language: php
php:
  - 5.4
  - 5.3
before_script:
  - pear install --alldeps PHP_CodeSniffer
  - phpenv rehash
  - git clone git://github.com/mrchrisadams/WordPress-Coding-Standards.git $(pear config-get php_dir)/PHP/CodeSniffer/Standards/WordPress
script:
  - phpcs --standard=WordPress ./src